# TODO: Add signing key and build app bundle
name: Build release APKs

on:
  workflow_dispatch:
    inputs:
      customTag:
        description: Custom tag
        type: string
        required: false

jobs:
  build-release-apks:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Write sign info
        if: github.repository_owner == 'k4ustu3h'
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi
      - name: Assign needed environment variables
        run: echo "CUSTOM_TAG=${{ github.event.inputs.customTag }}" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Prepare Offline Data for Izzy
        run: |
          pip install Pillow
          python download_contributor_data.py
      - name: Build release APKs
        run: ./gradlew clean assembleAppRelease assembleIzzyRelease
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: App Release APK
          path: app/build/outputs/apk/app/release/*.apk
      - name: Upload Izzy Artifact
        uses: actions/upload-artifact@v6
        with:
          name: Izzy Release APK
          path: app/build/outputs/apk/izzy/release/*.apk
